### ISSUE TITLE
The dragon hovered

### ISSUE THREAD

**Issue by DashRu** [MrGenie151/Ender-Dragon-Fight-Remastered#1]
The dragon broke, does not die and does not give an egg and an exit from the End

**Comment by MrGenie151** [comment]
Hm. Did you kill the miniboss the dragon spawns? Plus, I DO need to fix an urgent issue involving the end monument height. I will patch it soon.

**Comment by MrGenie151** [comment]
Patch added! Let me know if this fixed the problem.
