### ISSUE TITLE
"#Giant Stuff" hurt server that utilize `minecraft:giant` mob (like giant spawn naturally)

### ISSUE THREAD

**Issue by cupangafk** [MrGenie151/Ender-Dragon-Fight-Remastered#10]
idk what you thinking but 

DUDE, THIS HELL IS HURTING MY SERVER TPS

```
# Giant Stuff
execute as @e[type=minecraft:giant,tag=!init] at @s run summon giant ~ ~ ~ {Tags:["init","giant"],Passengers:[{id:"minecraft:zombie",NoAI:0b,Tags:["giant_brain","giant"],ActiveEffects:[{Id:14,Amplifier:1b,Duration:999999999999,ShowParticles:0b}]}],ArmorItems:[{},{},{},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTJhZjYyMzE4OTBiNjQ4MWFkN2Y5NWQxNTBhYzRkNDM3NDA1ODFlZjhiYTA3OTQ0ODc4M2VmYmVlOGVlZjljMCJ9fX0="}}]}
execute as @e[type=minecraft:giant,tag=!init] at @s run tp @s 0 0 0
execute as @e[tag=giant] unless entity @s[tag=!init] run function endfight:giant
```

like imagine we have 4 `minecraft:giant` spawn naturally

EVERY TICK THEY SPAWN ANOTHER GIANT IN THE `0 0 0` UNTIL IT WAS LIKE 200++ OF THEM

AND THE ENDER DRAGON FIGHT DOESNT EVEN HAVE GIANT FIGHT 

DUDE WHY

sorry bout the caps, but please fix this if possible

**Comment by cupangafk** [comment]
ps again: if this inappropriate please just delete this

**Comment by MrGenie151** [comment]
> idk what you thinking but
> 
> DUDE, THIS HELL IS HURTING MY SERVER TPS
> 
> ```
> # Giant Stuff
> execute as @e[type=minecraft:giant,tag=!init] at @s run summon giant ~ ~ ~ {Tags:["init","giant"],Passengers:[{id:"minecraft:zombie",NoAI:0b,Tags:["giant_brain","giant"],ActiveEffects:[{Id:14,Amplifier:1b,Duration:999999999999,ShowParticles:0b}]}],ArmorItems:[{},{},{},{id:"minecraft:player_head",Count:1b,tag:{SkullOwner:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTJhZjYyMzE4OTBiNjQ4MWFkN2Y5NWQxNTBhYzRkNDM3NDA1ODFlZjhiYTA3OTQ0ODc4M2VmYmVlOGVlZjljMCJ9fX0="}}]}
> execute as @e[type=minecraft:giant,tag=!init] at @s run tp @s 0 0 0
> execute as @e[tag=giant] unless entity @s[tag=!init] run function endfight:giant
> ```
> 
> like imagine we have 4 `minecraft:giant` spawn naturally
> 
> EVERY TICK THEY SPAWN ANOTHER GIANT IN THE `0 0 0` UNTIL IT WAS LIKE 200++ OF THEM
> 
> AND THE ENDER DRAGON FIGHT DOESNT EVEN HAVE GIANT FIGHT
> 
> DUDE WHY
> 
> sorry bout the caps, but please fix this if possible

Oops.

This was from an early stage of development when i wanted to make the dragon to spawn giants guess i forgot to remove it

I will mark it as urgent and remove the unused code from the datapack. Seriously sorry about that!

**Comment by MrGenie151** [comment]
It should be fixed now! Sorry for lagging the server im really sorry about that
