### ISSUE TITLE
How could I replace the battle music for my self-playing?

### ISSUE THREAD

**Issue by betterworld-sjq** [MrGenie151/Ender-Dragon-Fight-Remastered#14]
Yes, the music is great. But personally, I think phaseⅡ music is a bit too loud, so I'd like to replace it with a more gentle one myself for self-playing. But it seems not work if just replace the fight2.ogg file. Could you please solve my problem? Gratitude in advance!

**Comment by MrGenie151** [comment]
Are you using the mod or the data pack? If you are replacing fight2.ogg, try restarting your game or reloading the game's resources by pressing F3+T.

**Comment by betterworld-sjq** [comment]
In the form of mod.

**Comment by betterworld-sjq** [comment]
By the way, my fight2.ogg has just 5 min, but the origin one is about 20 min, would this affect the detection or something in game?

**Comment by betterworld-sjq** [comment]
Problem solved. I made my music to recycle up to 20 min, now it works!
