### ISSUE TITLE
The music is just copy and paste, and fading out is added by audio edition softwares.

### ISSUE THREAD

**Issue by zly2006** [MrGenie151/Ender-Dragon-Fight-Remastered#17]
I think you should not make the sound 4 times long, it costs 4 times unnecessary disk space and time to download it.

For example, Minecraft's music loop adds loops and fade out effects by java code, that may require making this a mod rather than a datapack. (or is datapack able to do this?)

p.s. I tried to phase-invert the original audio and overlaid it, there is only noises. I think reducing the size could be great for players.

**Comment by MrGenie151** [comment]
I did look into other, alternate ways of looping music before I decided to just make the audio file longer. I COULD try and make some sort of music timer for looping the music, and I might try it, but datapacks are quite difficult with things like this.
Talking about making it just a mod, I looked into that before making it a data pack. Part of what made me hesitant is that I'm not very good with Java or Kotlin, and rewriting the clunky dragon system would be complicated. I would kind of like to make it just a mod at some point, but I don't have the time to do that right now.
Thanks for your concern though! I appreciate the feedback, and things like this help me improve my stuff!

**Comment by zly2006** [comment]
oh i think I can provide some help for making it a mod, also, a mod can provide more custom sounds e.g. different sounds for the dragon flying around / perching, I think we can make more sounds to give a more immersive experience to players.

**Comment by MrGenie151** [comment]
Sorry for the late reply!
I would love some help turning this thing into a mod, but that might have to wait. I'm working on other projects at the moment, and they are eating up my time.
I am a bit curious though, what have you worked on before when it comes to MC modding?
Thanks!

**Comment by zly2006** [comment]
> what have you worked on before when it comes to MC modding?

just look at my github profile xd, almost all my mods are open sourced here.

**Comment by rcubedev** [comment]
You could use schedule function and create a dedicated function for music, and schedule clear <function> when dragon defeated

**Comment by rcubedev** [comment]
> You could use schedule function and create a dedicated function for music, and schedule clear when dragon defeated

I've swapped to scoreboard timers as they are easier to implement -> scheduled functions are ran as server even when a player executes the command.
