### ISSUE TITLE
This mod is ridiculously hard.

### ISSUE THREAD

**Issue by fahdicool5** [MrGenie151/Ender-Dragon-Fight-Remastered#20]
I read the description of this mod, and my fight was not the fight that was advertised to me. I know that this fight is supposed to be hard, but this was just absolutely ridiculous. Firstly, the ender dragon constantly has respawning ender dragon crystals(Even when not in the mad mode that it enters when dropped below 50 health), and aggros underman at you every minute. Spawns 2 blazes and a phantom every time you destroy a crystal. When it gets to 25% health, complete goes crazy and spawns a relentless lightning storm that made my game lag. I got it to 10% health multiple times, but it rebounded to 50% health in less than 3 minutes each time. Legit was impossible for me, and had to go into creative and kill it multiple time This mod legit sucked the fun out of this fight for me. My Netherite helmet broke, and the rest of my armor is at 10% durability. I popped 3 totems 30 golden apples gone. 3 stacks of food eaten.
I know this seems like just a bad review, but this I seriously think this mod was broken for me somehow. There was just no way that this fight could be THIS hard. This fight took me an hour and half before I gave up, and if the mod stays this way, I will never use it in a play through again.

**Comment by MrGenie151** [comment]
What you experienced was not what I intended... If I may ask what version
were you playing? I haven't had thr time to fully bugtest 1.20 so it may
have done some thing (enderman aggroing was broken in 1.19 to my
knowledge). Just know that the fight wasn't intended to be the diffuculty
you described it. I'm really sorry!

**Comment by fahdicool5** [comment]
Sorry for my earlier post, I was pretty frustrated with my experience with the fight since I sunk around 100 hours into my world, I'm sure you can understand where I was coming from. This was on the 1.20 version of the mod on a 1.21 multiplayer Fabric server. I'll definitely consider downloading the mod again if it's toned down a lot more lol. Thanks for your hard work developing this mod, I really like the idea (since the Ender Dragon fight is like, WAY too simple). If there's any other info you need for fixing it up I'll be happy to provide it.

**Comment by rcubedev** [comment]
The mod you downloaded is likely different as this doesn't spawn mobs upon the destruction of an end crystal, nor does it respawn crystals at 25% health (instead respawning 3 at 50%).
