### ISSUE TITLE
Ender Dragon is 1 Shot with any melee kill

### ISSUE THREAD

**Issue by cheesebobi** [MrGenie151/Ender-Dragon-Fight-Remastered#24]
Hello, Im currently developing a fabric modpack and I really like your ender dragon fight remaster datapack. However, I have a major problem, the ender dragon is 1 shot when hit with a melee attack first, this isn't normally a problem in vanilla but in modded there are ways of flight and hitting the dragon is rather easy. Is this something you could look into?

Minecraft: 1.19.4
Mod Loader: Fabric

Video Showing The Issue:
https://www.youtube.com/watch?v=FGlp-Y0E-fY&feature=youtu.be

**Comment by rcubedev** [comment]
Cannot reproduce

**Comment by rcubedev** [comment]
What additional mobs do you have?

**Comment by cheesebobi** [comment]
Hello! Terribly sorry forgot to update this, the issue stemmed from the Death Scythe mod, not this mod/datapack. This can be considered closed.
