### ISSUE TITLE
Make a version without phase 2 song

### ISSUE THREAD

**Issue by Lize58** [MrGenie151/Ender-Dragon-Fight-Remastered#33]
I really like the phase 1 song for the mod, but everything gets ruined by the second phase song. Is there a chance to get the mod without the phase 2 song, so that only the phase 1 song stays?

**Comment by rcubedev** [comment]
IMO, this isn't work it as this would require having two different releases

If/when a config gets added (PR's are welcome!), this could be implemented as part of it.

**Comment by rcubedev** [comment]
Oops... I keep pressing the wrong buttons accidentally..
