### ISSUE TITLE
Unusable mod

### ISSUE THREAD

**Issue by Skidamek** [MrGenie151/Ender-Dragon-Fight-Remastered#5]
I only have tested latest mod version from modrinth. And well probably this mod seems cool but something  is definitely wrong...
It spawns A LOT of entities (probably armor stands on top of end portal) in end. At least only them I saw on spectator while testing on sigleplayer. It lags my game so much (5 fps) and not only it. Even server has problem with it. I experiencing big lag spike on server every 5-10 minutes for 10 seconds while no one is/was even in end. I only pregen it before with chunky.

[19:50:25] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 13372ms or 267 ticks behind
[19:55:29] [C2ME Storage #7/WARN]: Saving oversized chunk [0, 0] (351866610 bytes} to external file ./world/DIM1/entities/c.0.0.mcc
[19:55:35] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 14531ms or 290 ticks behind

**Comment by DecDuck** [comment]
I'm having the same issue. The spark profiler said that the Unsafe.park() function was taking a while. Maybe that helps.

**Comment by MrGenie151** [comment]
This is an issue I have had too. Marked as URGENT!!!!

**Comment by MrGenie151** [comment]
Attempted to fix it, download the new version and tell me if it works please!

**Comment by Skidamek** [comment]
Seems to work fine, thank you!
