### ISSUE TITLE
Buggy music

### ISSUE THREAD

**Issue by realShaiw** [MrGenie151/Ender-Dragon-Fight-Remastered#8]
Upon dying, you will not hear any music anymore.

It really kills the immersion of the fight.

P.S. It happened on Fabric with the mod version 4.2.0

**Comment by Shaiw1** [comment]
Also, when the Warror mini-boss spawns, the Ender Dragon stands still in the center allowing you to spam arrows at her, so I would suggest to grant her an arrow immunity until the mini-boss dies.

**Comment by MrGenie151** [comment]
> Upon dying, you will not hear any music anymore.
> 
> It really kills the immersion of the fight.
> 
> P.S. It happened on Fabric with the mod version 4.2.0

Ooh, this is a toughie. This is a datapack at it's core, and it makes adding music REALLY hard. I had the music cut out during testing and it is really good at killing the immersion, but at current moment there is no way to detect if a specific sound is playing.

P.S. Just thought of a way to detect if a sound is playing. May fix in a future update also testing compatibility with 1.20

**Comment by Shaiw1** [comment]
Thanks!

Also, there is an extended version of Univeral Collapse on Soundcloud that retains the high quality audio instad of youtube that compresses it. (https://soundcloud.com/raichu-thunder/extended-calamity-mod-music-universal-collapse-1-hour)

This should help fixing the bad loop during the second phase.
